### PR TITLE
added the commits to Branch x

### PR DESCRIPTION
**Pull request by mahajan-projects**
added new testcases to branch x 
please review this
regards,
x

### CODE REVIEW

**Comment by mahajan-projects** [comment]
hi add code to the 4th commit
regards,
MM

**Comment by MAYURIMAHAJAN123** [comment]
Add new testcases for Negetive testing....

**Comment by mahajan-projects** [comment]
Added the testcases...

**Comment by mahajan-projects** [comment]
now merge the pull request

**Pull request merged**
